
project_id = "fdezrtfnjsweyoborhwg"

[[functions]]
[functions.deepseek-process]
verify_jwt = false

[[functions]]
[functions.lmstudio-process]
verify_jwt = false

[[functions]]
[functions.weather-data]
verify_jwt = false

