
project_id = "fdezrtfnjsweyoborhwg"

[[functions]]
name = "deepseek-process"
verify_jwt = false

[[functions]]
name = "lmstudio-process"
verify_jwt = false

[[functions]]
name = "weather-data"
verify_jwt = false
