version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL:-http://localhost:54321}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-local-anon-key}
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_PROJECT=MNTRK Vocal
    depends_on:
      - db
      - api
      - agent
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mostar
      POSTGRES_DB: mntracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./Backend/API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:mostar@db:5432/mntracker
    depends_on:
      - db

  agent:
    build:
      context: ./Backend/Agent
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:mostar@db:5432/mntracker
    depends_on:
      - db

volumes:
  postgres_data: