// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuuvziezowtxwnlbziod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dXZ6aWV6b3d0eHdubGJ6aW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NDQ1NDMsImV4cCI6MjA1MDUyMDU0M30.xChDfVG49JMCkHz-LGKjhTNDxGfhEhBj_Ry96DaRfK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);