// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbdolxktrprksjwtokml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZG9seGt0cnBya3Nqd3Rva21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0Mjc1MzgsImV4cCI6MjA1MTAwMzUzOH0.8qmjuBeZ4OrgW00AVVkU35RuDhtSz9WvS-_uVTwUIuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);