# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.8"  # Updated to a more recent version
  - "3.9"
  - "3.10"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
